### ISSUE TITLE
我怎么注册呢？

### ISSUE THREAD

**Issue by 1264967889** [TikHubIO/TikHub-API-Python-SDK#10]
我该怎么注册邮箱呢，token的过期时间是多久呢？

**Comment by Evil0ctal** [comment]
加一下机器人微信：Evil-Bot

**Comment by bxiaoj** [comment]
> 我该怎么注册邮箱呢，token的过期时间是多久呢？

[http://vproctol.zeed.ink/](http://vproctol.zeed.ink/)可以用，能解决你的问题，免费稳定（突破黑名单和IP限制）
