### ISSUE TITLE
注册不了，请问怎么注册呢？微信也添加不了，账号违规了

### ISSUE THREAD

**Issue by liulu1550** [TikHubIO/TikHub-API-Python-SDK#16]
注册不了，请问怎么注册呢？微信也添加不了，账号违规了

**Comment by Evil0ctal** [comment]
用这个：

https://dash.tikhub.io/

**Comment by yessfadfsdfa** [comment]
注册不了，一直提示“密码要8～18字符xxxxx”

**Comment by bxiaoj** [comment]
[http://vproctol.zeed.ink/](http://vproctol.zeed.ink/)可以用，能解决你的问题，免费稳定
