### ISSUE TITLE
请问有单独根据主页界面抓取主页信息的api吗

### ISSUE THREAD

**Issue by woniuxia** [TikHubIO/TikHub-API-Python-SDK#18]
我看了下全部都是需要从视频页链接才能抓取到主页相关信息。
我当前的需求根据用户名抓取对应的头像以及粉丝数。
请问有相关的api吗？我没找到。

**Comment by Evil0ctal** [comment]
tt暂时没有，但是很快会加上。

**Comment by woniuxia** [comment]
请问大概会在什么时间上线，最近就有需求

**Comment by bxiaoj** [comment]
[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.
