### ISSUE TITLE
调用抖音获取评论api失败

### ISSUE THREAD

**Issue by wanghchen** [TikHubIO/TikHub-API-Python-SDK#19]
在调用douyin_api.get_douyin_video_comments()方法时，返回结果为：
{
  "status": false,
  "platform": "douyin",
  "endpoint": "/douyin/video_comments/",
  "total_time": null,
  "message": "解析失败，检查参数/Parse failed, check parameters",
  "video_id": null,
  "has_more": null,
  "cursor": null,
  "next_url": null,
  "count": null,
  "comments_list": null
}
但需输入的参数都已输入，且已添加token因此想询问下可能的原因，谢谢。

**Comment by lzyLuke** [comment]
相同问题+1

**Comment by ysyszheng** [comment]
`get_tiktok_video_comments()`同样显示`解析失败，检查参数/Parse failed, check parameters`
