### ISSUE TITLE
请求抖音评论接口报错了

### ISSUE THREAD

**Issue by jqsl2012** [TikHubIO/TikHub-API-Python-SDK#25]
{
  "status": false,
  "platform": "douyin",
  "endpoint": "/douyin/video_comments/",
  "total_time": null,
  "message": "解析失败，检查参数/Parse failed, check parameters",
  "video_id": null,
  "has_more": null,
  "cursor": null,
  "next_url": null,
  "count": null,
  "comments_list": null
}

**Comment by avadasma** [comment]
平台：douyin
接口：/douyin/user_profile_videos_data/
{
"status": false,
"platform": "douyin",
"endpoint": "/douyin/user_profile_videos_data/",
"total_time": null,
"message": "解析失败，检查参数/Parse failed, check parameters",
"video_id": null,
"sec_user_id": null,
"has_more": null,
"cursor": null,
"next_url": null,
"count": null,
"aweme_list": null
}
