### ISSUE TITLE
充值问题

### ISSUE THREAD

**Issue by xyq043170** [TikHubIO/TikHub-API-Python-SDK#29]
你们这个没有免费额度，试用都不让试用就让充值啊？

**Comment by Evil0ctal** [comment]
#### 用户

* **官网/用户后台/用户支付** : [TikHub User](https://beta-web.tikhub.io/users/signin)

#### 更新通知

* **旧用户**
  * 如果您之前已注册TikHub账户，请重新注册，并通过Discord、微信或电子邮件联系我们以调整剩余余额，我们会一对一为您服务。
* **新用户**
  * 请注册并**验证邮箱**后，才能使用API及购买服务。
* **支付**
  * Stripe支付: 支持Visa、MasterCard、American Express等信用卡，以及Apple Pay、Google Pay等支付方式。
  * PayPal支付: 中国用户/银联卡 请使用PayPal支付，支付时 **不强制要求注册** ，请选择下方的信用卡/借记卡支付选项。
  * Unipayment支付: 支持USDT、BTC、ETH等加密货币支付。
  * 如果以上支付方式无法满足您的需求，请联系我们。
* **推荐码**
  * 您可以将推荐码注册链接发送给朋友，如果朋友注册成功，您将获得2美元的付费余额（约1000次请求量），您的朋友在第一次购买服务后也将获得2美元的付费余额（约1000次请求量）。
  * 推荐码注册链接在个人主页中查看和生成
  * 推荐码注册链接有效期为30天
  * 使用推荐码的时候要确保您的账户已验证邮箱并且是付费用户
* **API Key使用**
  * 请在生成API Key后立即保存，因为API Key只会在创建后显示一次。
  * 每位用户最多可创建20个API Key。
* **API免费试用**
  * 每个用户注册并且验证邮箱后，可以在用户后台的右上角点击签到按钮，获取免费试用额度，每天可以签到一次。

**Comment by Evil0ctal** [comment]
请仔细阅读文档：

https://api.tikhub.io/

或

https://docs.tikhub.io/
