### ISSUE TITLE
充了钱根本不能用 挺无语的

### ISSUE THREAD

**Issue by JessyTsui** [TikHubIO/TikHub-API-Python-SDK#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Evil0ctal** [comment]
不能用就去联系客服解决，我们在Discord服务器基本上都是30分钟内回复的，不要上来就一句不能用，我都不清楚是接口风控了，还是你操作有误，再说了，API都是有风控的，人家开发者变更了风控机制我们也要去花时间更新，并且我们每周都在更新和维护现有的接口，不要上来就一句充了钱不能用，然后什么细节都不提供，如果你真的充了钱，发送你的账号信息至`tikhub.io@proton.me`，我们给你做refund处理，并且平台本身就是每天都有免费的请求次数可以用于测试用途，你充值前没有测试你要用的接口吗？
